### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the CI/CD pipeline. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 9757096268 for 64bf1c12fd3ee2cf4002c1b33f43ac780ec929c3

https://github.com/MatrixAI/js-rpc/actions/runs/9757096268

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 9757310588 for b9045bde1fd278b270fb63a42c73962eb010b56f

https://github.com/MatrixAI/js-rpc/actions/runs/9757310588

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 9757734397 for ed558529ef5da8a17f7f37b3b7d1a11c835f3c09

https://github.com/MatrixAI/js-rpc/actions/runs/9757734397

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 9769204923 for 79a38503e1e9d26f2ca4ec6400ffc831bc11e170

https://github.com/MatrixAI/js-rpc/actions/runs/9769204923

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 11266517328 for bd752cc9c78524fe488ebbd9774eb8269166b32a

https://github.com/MatrixAI/js-rpc/actions/runs/11266517328

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 11733584104 for 3216c85a633c4fe11e5bf22c9a3405967b923892

https://github.com/MatrixAI/js-rpc/actions/runs/11733584104

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 11736376716 for d1f90a76129482da3e9b43a2ac27ba846f5769d0

https://github.com/MatrixAI/js-rpc/actions/runs/11736376716

**Comment by CMCDragonkai** [comment]
How come this PR still has alot of @brynblack commits?

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 11736376716 for d1f90a76129482da3e9b43a2ac27ba846f5769d0

https://github.com/MatrixAI/js-rpc/actions/runs/11736376716

**Pull request merged**
