### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the CI/CD pipeline. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 12193415711 for 22c79e1024c05eccdf0371b6a435a50a8e0c78ba

https://github.com/MatrixAI/js-rpc/actions/runs/12193415711

**Comment by aryanjassal** [comment]
https://github.com/MatrixAI/js-rpc/actions/runs/12193415711/job/34015714661

This job had a failed Windows test, but the Windows build job appears as successful. If the CI is passing failing jobs, then this is very bad. Look into this, @brynblack.

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 12193566014 for 6cc6fde7608ef82512a54c86cf3d08f9bd7ae4eb

https://github.com/MatrixAI/js-rpc/actions/runs/12193566014

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 12193566014 for 6cc6fde7608ef82512a54c86cf3d08f9bd7ae4eb

https://github.com/MatrixAI/js-rpc/actions/runs/12193566014

**Comment by tegefaulkes** [comment]
> https://github.com/MatrixAI/js-rpc/actions/runs/12193415711/job/34015714661
> 
> This job had a failed Windows test, but the Windows build job appears as successful. If the CI is passing failing jobs, then this is very bad. Look into this, @brynblack.

You should make an issue for this with details.

**Comment by aryanjassal** [comment]
https://github.com/MatrixAI/js-rpc/issues/76

**Pull request merged**
